@startuml
skinparam monochrome true
skinparam shadowing false
hide footbox

box "Logic" #LightBlue
participant "<<class>>\nParser" as Parser
participant "d:EditQuantityCommand" as EditQuantityCommand
participant "v:EditQuantityCommandValidator" as EditQuantityCommandValidator
end box

box "Data" #LightYellow
participant "items:ItemList" as ItemList
participant "item:Item" as Item
end box

box "UI" #LightGreen
participant "ui:Ui" as Ui
end box

-> Parser : parse("editQuantity 1 q/20", items, ui)
activate Parser

create EditQuantityCommand
Parser -> EditQuantityCommand : new EditQuantityCommand(input)
activate EditQuantityCommand
EditQuantityCommand --> Parser : d
deactivate EditQuantityCommand

Parser -> EditQuantityCommand : execute(items, ui)
activate EditQuantityCommand

create EditQuantityCommandValidator
EditQuantityCommand -> EditQuantityCommandValidator : new EditQuantityCommandValidator(input)
activate EditQuantityCommandValidator
EditQuantityCommandValidator --> EditQuantityCommand : v
deactivate EditQuantityCommandValidator

EditQuantityCommand -> EditQuantityCommandValidator : validate(items)
activate EditQuantityCommandValidator
note right of EditQuantityCommandValidator
  Checks format, index bounds,
  and non-negative quantity
end note
EditQuantityCommandValidator --> EditQuantityCommand
deactivate EditQuantityCommandValidator
EditQuantityCommandValidator -[hidden]-> EditQuantityCommand
destroy EditQuantityCommandValidator

EditQuantityCommand -> ItemList : getItem(index)
activate ItemList
ItemList --> EditQuantityCommand : item
deactivate ItemList

EditQuantityCommand -> Item : setQuantity(newQuantity)
activate Item
Item --> EditQuantityCommand
deactivate Item

EditQuantityCommand -> Ui : showMessage("Item quantity updated: " + item)
activate Ui
Ui --> EditQuantityCommand
deactivate Ui

EditQuantityCommand --> Parser
deactivate EditQuantityCommand
EditQuantityCommand -[hidden]-> Parser
destroy EditQuantityCommand

<-- Parser
deactivate Parser

@enduml
