@startuml
!pragma teoz true
skinparam monochrome true
skinparam shadowing false

box "Logic" #LightBlue
participant "<<class>>\nParser" as Parser
participant "h:HelpCommand" as HelpCommand
participant "v:HelpCommandValidator" as HelpCommandValidator
end box

box "UI" #LightGreen
participant "ui:Ui" as Ui
end box

-> Parser : parse("help", items, ui)
activate Parser

create HelpCommand
Parser -> HelpCommand : new HelpCommand("help")
activate HelpCommand
HelpCommand --> Parser : h
deactivate HelpCommand

Parser -> HelpCommand : execute(items, ui)
activate HelpCommand

create HelpCommandValidator
HelpCommand -> HelpCommandValidator : new HelpCommandValidator("help")
activate HelpCommandValidator
HelpCommandValidator --> HelpCommand : v
deactivate HelpCommandValidator

HelpCommand -> HelpCommandValidator : validate(items)
activate HelpCommandValidator
HelpCommandValidator --> HelpCommand
deactivate HelpCommandValidator

alt Input is only "help"
    HelpCommand -> HelpCommand : info = HELPSUMMARYMESSAGE
else Input is "help [command_name]"
    HelpCommand -> HelpCommand : info = COMMANDMESSAGES([command_name])
end

HelpCommand -> Ui : showMessage(info)
activate Ui
Ui --> HelpCommand
deactivate Ui

HelpCommand --> Parser
deactivate HelpCommand

<-- Parser
deactivate Parser

@enduml