@startuml
'https://plantuml.com/class-diagram

skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam packageFontSize 40
skinparam classFontSize 35
skinparam classAttributeFontSize 46
skinparam classStereotypeFontSize 40
skinparam ArrowThickness 4
hide circle

package "seedu.inventorybro" {
    class InventoryBro #mediumorchid {
        - ui: Ui
        - items: ItemList
        - arrayStorage: ArrayStorage
    }

    class Ui #mediumpurple
    class Parser #palegoldenrod
    class TypoDetector #springgreen
    enum CommandWord <<enumeration>> #mediumpurple

    package "command" {
        interface Command <<interface>> #mediumseagreen

        class AddCommand #limegreen
        class DeleteCommand #limegreen
        class EditDescriptionCommand #limegreen
        class EditPriceCommand #limegreen
        class EditQuantityCommand #limegreen
        class TransactCommand #limegreen
        class ShowTransactionHistoryCommand #limegreen
        class ListCommand #limegreen
        class FindCommand #limegreen
        class FilterCommand #limegreen
        class HelpCommand #limegreen
        class ExitCommand #limegreen
    }

    package "storage" {
        abstract class Storage #mediumturquoise
        class ArrayStorage #turquoise
        class TransactionStorage #turquoise
    }

    class ItemList #lightyellow
    class Item #yellow

    package "validator" {
        interface Validator <<interface>> #lightcoral

        class AddCommandValidator #orange
        class DeleteCommandValidator #orange
        class DuplicateItemValidator #orange
        class EditDescriptionCommandValidator #orange
        class EditPriceCommandValidator #orange
        class EditQuantityCommandValidator #orange
        class FilterCommandValidator #orange
        class FindCommandValidator #orange
        class HelpCommandValidator #orange
        class ListCommandValidator #orange
        class ShowTransactionHistoryCommandValidator #orange
        class TransactCommandValidator #orange
    }

    package "autocomplete" {
        class Autocompleter #deepskyblue
        class Trie #lightskyblue
        class TrieNode #powderblue
    }

    'main alignment
    Parser -[hidden]down-> "storage"
    "command" -[hidden]right-> "validator"

    'Main
    InventoryBro .down.> Parser
    Parser .right.> Command
    InventoryBro -down-> Ui
    Parser .left.> Ui
    Parser -right-> TypoDetector
    InventoryBro --> ArrayStorage
    Autocompleter -up-* Ui
    Autocompleter ..> CommandWord
    HelpCommandValidator ..> CommandWord
    InventoryBro --> ItemList

    'storage
    ArrayStorage -up-|> Storage
    TransactionStorage -up-|> Storage
    ArrayStorage --|> ItemList
    ItemList --|> Item

    TransactCommand -down-> TransactionStorage
    ShowTransactionHistoryCommand -down-> TransactionStorage

    'autocomplete
    TrieNode -up-* Trie
    Trie -up-* Autocompleter

    'Alignment
    AddCommand -[hidden]down-> DeleteCommand
    DeleteCommand -[hidden]down-> EditDescriptionCommand
    EditDescriptionCommand -[hidden]down-> EditPriceCommand
    EditPriceCommand -[hidden]down-> EditQuantityCommand
    EditQuantityCommand -[hidden]down-> ExitCommand
    ExitCommand -[hidden]down-> FilterCommand
    FilterCommand -[hidden]down-> FindCommand
    FindCommand -[hidden]down-> HelpCommand
    HelpCommand -[hidden]down-> ListCommand
    ListCommand -[hidden]down-> ShowTransactionHistoryCommand
    ShowTransactionHistoryCommand -[hidden]down-> TransactCommand

    AddCommandValidator -[hidden]down-> DeleteCommandValidator
    DeleteCommandValidator -[hidden]down-> EditDescriptionCommandValidator
    EditDescriptionCommandValidator -[hidden]down-> EditPriceCommandValidator
    EditPriceCommandValidator -[hidden]down-> EditQuantityCommandValidator
    EditQuantityCommandValidator -[hidden]down-> FilterCommandValidator
    FilterCommandValidator -[hidden]down-> FindCommandValidator
    FindCommandValidator -[hidden]down-> HelpCommandValidator
    HelpCommandValidator -[hidden]down-> ListCommandValidator
    ListCommandValidator -[hidden]down-> ShowTransactionHistoryCommandValidator
    ShowTransactionHistoryCommandValidator -[hidden]down-> TransactCommandValidator

    'Commands to CommandValidators
    AddCommand ..> AddCommandValidator
    DeleteCommand ..> DeleteCommandValidator
    EditDescriptionCommand ..> EditDescriptionCommandValidator
    EditPriceCommand ..> EditPriceCommandValidator
    EditQuantityCommand ..> EditQuantityCommandValidator
    FilterCommand ..> FilterCommandValidator
    FindCommand ..> FindCommandValidator
    HelpCommand ..> HelpCommandValidator
    ListCommand ..> ListCommandValidator
    ShowTransactionHistoryCommand ..> ShowTransactionHistoryCommandValidator
    TransactCommand ..> TransactCommandValidator

    'Commands to Command interface
    AddCommand .left.|> Command
    DeleteCommand .left.|> Command
    EditDescriptionCommand .left.|> Command
    EditPriceCommand .left.|> Command
    EditQuantityCommand .left.|> Command
    ExitCommand .left.|> Command
    FilterCommand .left.|> Command
    FindCommand .left.|> Command
    HelpCommand .left.|> Command
    ListCommand .left.|> Command
    ShowTransactionHistoryCommand .left.|> Command
    TransactCommand .left.|> Command

    'CommandValidators to Validator interface
    DuplicateItemValidator <-- AddCommandValidator
    Validator <|.right. AddCommandValidator
    Validator <|.right. DuplicateItemValidator
    Validator <|.right. DeleteCommandValidator
    Validator <|.right. EditDescriptionCommandValidator
    Validator <|.right. EditPriceCommandValidator
    Validator <|.right. EditQuantityCommandValidator
    Validator <|.right. FilterCommandValidator
    Validator <|.right. FindCommandValidator
    Validator <|.right. HelpCommandValidator
    Validator <|.right. ListCommandValidator
    Validator <|.right. ShowTransactionHistoryCommandValidator
    Validator <|.right. TransactCommandValidator
}

@enduml